//
// DirectionsMatrixSources.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation



public struct DirectionsMatrixSources: Codable {

    public var distance: Double?
    public var location: [Double]?
    public var name: String?

    public init(distance: Double?, location: [Double]?, name: String?) {
        self.distance = distance
        self.location = location
        self.name = name
    }


}

