//
// DirectionsNearest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation



public struct DirectionsNearest: Codable {

    public var code: String?
    public var waypoints: [DirectionsNearestWaypoints]?

    public init(code: String?, waypoints: [DirectionsNearestWaypoints]?) {
        self.code = code
        self.waypoints = waypoints
    }


}

