//
// DirectionsMatrix.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation



public struct DirectionsMatrix: Codable {

    public var code: String?
    public var distances: [Double]?
    public var fallbackSpeedCells: [Double]?
    public var sources: [DirectionsMatrixSources]?
    public var destinations: [DirectionsMatrixSources]?

    public init(code: String?, distances: [Double]?, fallbackSpeedCells: [Double]?, sources: [DirectionsMatrixSources]?, destinations: [DirectionsMatrixSources]?) {
        self.code = code
        self.distances = distances
        self.fallbackSpeedCells = fallbackSpeedCells
        self.sources = sources
        self.destinations = destinations
    }

    public enum CodingKeys: String, CodingKey { 
        case code
        case distances
        case fallbackSpeedCells = "fallback_speed_cells"
        case sources
        case destinations
    }


}

