//
// Location.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation



public struct Location: Codable {

    public var distance: Double?
    public var placeId: String?
    public var licence: String?
    public var osmType: String?
    public var osmId: String?
    public var boundingbox: [String]?
    public var lat: String?
    public var lon: String?
    public var displayName: String?
    public var _class: String?
    public var type: String?
    public var importance: Double?
    public var address: Address?
    public var namedetails: Namedetails?
    public var matchquality: Matchquality?

    public init(distance: Double?, placeId: String?, licence: String?, osmType: String?, osmId: String?, boundingbox: [String]?, lat: String?, lon: String?, displayName: String?, _class: String?, type: String?, importance: Double?, address: Address?, namedetails: Namedetails?, matchquality: Matchquality?) {
        self.distance = distance
        self.placeId = placeId
        self.licence = licence
        self.osmType = osmType
        self.osmId = osmId
        self.boundingbox = boundingbox
        self.lat = lat
        self.lon = lon
        self.displayName = displayName
        self._class = _class
        self.type = type
        self.importance = importance
        self.address = address
        self.namedetails = namedetails
        self.matchquality = matchquality
    }

    public enum CodingKeys: String, CodingKey { 
        case distance
        case placeId = "place_id"
        case licence
        case osmType = "osm_type"
        case osmId = "osm_id"
        case boundingbox
        case lat
        case lon
        case displayName = "display_name"
        case _class = "class"
        case type
        case importance
        case address
        case namedetails
        case matchquality
    }


}

