//
// BalanceAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation



open class BalanceAPI {
    /**

     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func balance(completion: @escaping ((_ data: Balance?,_ error: Error?) -> Void)) {
        balanceWithRequestBuilder().execute { (response, error) -> Void in
            completion(response?.body, error)
        }
    }

    /**
     - GET /balance.php
     - The Balance API provides a count of request credits left in the user's account for the day. Balance is reset at midnight UTC everyday (00:00 UTC).
     - API Key:
       - type: apiKey key (QUERY)
       - name: key
     - returns: RequestBuilder<Balance> 
     */
    open class func balanceWithRequestBuilder() -> RequestBuilder<Balance> {
        let path = "/balance.php"
        let URLString = OpenAPIClientAPI.basePath + path
        let parameters: [String:Any]? = nil
        
        let url = URLComponents(string: URLString)

        let requestBuilder: RequestBuilder<Balance>.Type = OpenAPIClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false)
    }

}
