//
// DirectionsAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation



open class DirectionsAPI {
    /**
     Directions Service
     
     - parameter coordinates: (path) String of format {longitude},{latitude};{longitude},{latitude}[;{longitude},{latitude} ...] or polyline({polyline}) or polyline6({polyline6}). polyline follows Google&#39;s polyline format with precision 5 
     - parameter bearings: (query) Limits the search to segments with given bearing in degrees towards true north in clockwise direction. List of positive integer pairs separated by semi-colon and bearings array should be equal to length of coordinate array. Input Value :- {bearing};{bearing}[;{bearing} ...] Bearing follows the following format : bearing {value},{range} integer 0 .. 360,integer 0 .. 180 (optional)
     - parameter radiuses: (query) Limits the search to given radius in meters Radiuses array length should be same as coordinates array, eaach value separated by semi-colon. Input Value - {radius};{radius}[;{radius} ...] Radius has following format :- double &gt;&#x3D; 0 or unlimited (default) (optional)
     - parameter generateHints: (query) Adds a Hint to the response which can be used in subsequent requests, see hints parameter. Input Value - true (default), false Format - Base64 String (optional)
     - parameter approaches: (query) Keep waypoints on curb side. Input Value - {approach};{approach}[;{approach} ...] Format - curb or unrestricted (default) (optional)
     - parameter exclude: (query) Additive list of classes to avoid, order does not matter. input Value - {class}[,{class}] Format - A class name determined by the profile or none. (optional)
     - parameter alternatives: (query) Search for alternative routes. Passing a number alternatives&#x3D;n searches for up to n alternative routes. [ true, false (default), or Number ] (optional)
     - parameter steps: (query) Returned route steps for each route leg [ true, false (default) ] (optional)
     - parameter annotations: (query) Returns additional metadata for each coordinate along the route geometry.  [ true, false (default), nodes, distance, duration, datasources, weight, speed ] (optional, default to "\"false\"")
     - parameter geometries: (query) Returned route geometry format (influences overview and per step) [ polyline (default), polyline6, geojson ] (optional, default to "\"polyline\"")
     - parameter overview: (query) Add overview geometry either full, simplified according to highest zoom level it could be display on, or not at all. [ simplified (default), full, false ] (optional, default to "\"simplified\"")
     - parameter continueStraight: (query) Forces the route to keep going straight at waypoints constraining uturns there even if it would be faster. Default value depends on the profile [ default (default), true, false ] (optional, default to "\"default\"")
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func directions(coordinates: String, bearings: String? = nil, radiuses: String? = nil, generateHints: String? = nil, approaches: String? = nil, exclude: String? = nil, alternatives: Double? = nil, steps: String? = nil, annotations: String? = nil, geometries: String? = nil, overview: String? = nil, continueStraight: String? = nil, completion: @escaping ((_ data: DirectionsDirections?,_ error: Error?) -> Void)) {
        directionsWithRequestBuilder(coordinates: coordinates, bearings: bearings, radiuses: radiuses, generateHints: generateHints, approaches: approaches, exclude: exclude, alternatives: alternatives, steps: steps, annotations: annotations, geometries: geometries, overview: overview, continueStraight: continueStraight).execute { (response, error) -> Void in
            completion(response?.body, error)
        }
    }

    /**
     Directions Service
     - GET /directions/driving/{coordinates}
     - Finds the fastest route between coordinates in the supplied order.
     - API Key:
       - type: apiKey key (QUERY)
       - name: key
     - parameter coordinates: (path) String of format {longitude},{latitude};{longitude},{latitude}[;{longitude},{latitude} ...] or polyline({polyline}) or polyline6({polyline6}). polyline follows Google&#39;s polyline format with precision 5 
     - parameter bearings: (query) Limits the search to segments with given bearing in degrees towards true north in clockwise direction. List of positive integer pairs separated by semi-colon and bearings array should be equal to length of coordinate array. Input Value :- {bearing};{bearing}[;{bearing} ...] Bearing follows the following format : bearing {value},{range} integer 0 .. 360,integer 0 .. 180 (optional)
     - parameter radiuses: (query) Limits the search to given radius in meters Radiuses array length should be same as coordinates array, eaach value separated by semi-colon. Input Value - {radius};{radius}[;{radius} ...] Radius has following format :- double &gt;&#x3D; 0 or unlimited (default) (optional)
     - parameter generateHints: (query) Adds a Hint to the response which can be used in subsequent requests, see hints parameter. Input Value - true (default), false Format - Base64 String (optional)
     - parameter approaches: (query) Keep waypoints on curb side. Input Value - {approach};{approach}[;{approach} ...] Format - curb or unrestricted (default) (optional)
     - parameter exclude: (query) Additive list of classes to avoid, order does not matter. input Value - {class}[,{class}] Format - A class name determined by the profile or none. (optional)
     - parameter alternatives: (query) Search for alternative routes. Passing a number alternatives&#x3D;n searches for up to n alternative routes. [ true, false (default), or Number ] (optional)
     - parameter steps: (query) Returned route steps for each route leg [ true, false (default) ] (optional)
     - parameter annotations: (query) Returns additional metadata for each coordinate along the route geometry.  [ true, false (default), nodes, distance, duration, datasources, weight, speed ] (optional, default to "\"false\"")
     - parameter geometries: (query) Returned route geometry format (influences overview and per step) [ polyline (default), polyline6, geojson ] (optional, default to "\"polyline\"")
     - parameter overview: (query) Add overview geometry either full, simplified according to highest zoom level it could be display on, or not at all. [ simplified (default), full, false ] (optional, default to "\"simplified\"")
     - parameter continueStraight: (query) Forces the route to keep going straight at waypoints constraining uturns there even if it would be faster. Default value depends on the profile [ default (default), true, false ] (optional, default to "\"default\"")
     - returns: RequestBuilder<DirectionsDirections> 
     */
    open class func directionsWithRequestBuilder(coordinates: String, bearings: String? = nil, radiuses: String? = nil, generateHints: String? = nil, approaches: String? = nil, exclude: String? = nil, alternatives: Double? = nil, steps: String? = nil, annotations: String? = nil, geometries: String? = nil, overview: String? = nil, continueStraight: String? = nil) -> RequestBuilder<DirectionsDirections> {
        var path = "/directions/driving/{coordinates}"
        let coordinatesPreEscape = "\(APIHelper.mapValueToPathItem(coordinates))"
        let coordinatesPostEscape = coordinatesPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        path = path.replacingOccurrences(of: "{coordinates}", with: coordinatesPostEscape, options: .literal, range: nil)
        let URLString = OpenAPIClientAPI.basePath + path
        let parameters: [String:Any]? = nil
        
        var url = URLComponents(string: URLString)
        url?.queryItems = APIHelper.mapValuesToQueryItems([
            "bearings": bearings?.encodeToJSON(), 
            "radiuses": radiuses?.encodeToJSON(), 
            "generate_hints": generateHints?.encodeToJSON(), 
            "approaches": approaches?.encodeToJSON(), 
            "exclude": exclude?.encodeToJSON(), 
            "alternatives": alternatives?.encodeToJSON(), 
            "steps": steps?.encodeToJSON(), 
            "annotations": annotations?.encodeToJSON(), 
            "geometries": geometries?.encodeToJSON(), 
            "overview": overview?.encodeToJSON(), 
            "continue_straight": continueStraight?.encodeToJSON()
        ])

        let requestBuilder: RequestBuilder<DirectionsDirections>.Type = OpenAPIClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false)
    }

}
