//
// Address.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation



public struct Address: Codable {

    public var houseNumber: String?
    public var road: String?
    public var residential: String?
    public var village: String?
    public var county: String?
    public var state: String?
    public var postcode: String?
    public var country: String?
    public var countryCode: String?
    public var city: String?

    public init(houseNumber: String?, road: String?, residential: String?, village: String?, county: String?, state: String?, postcode: String?, country: String?, countryCode: String?, city: String?) {
        self.houseNumber = houseNumber
        self.road = road
        self.residential = residential
        self.village = village
        self.county = county
        self.state = state
        self.postcode = postcode
        self.country = country
        self.countryCode = countryCode
        self.city = city
    }

    public enum CodingKeys: String, CodingKey { 
        case houseNumber = "house_number"
        case road
        case residential
        case village
        case county
        case state
        case postcode
        case country
        case countryCode = "country_code"
        case city
    }


}

