//
// Balance.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation



public struct Balance: Codable {

    public var status: String?
    public var balance: Daybalance?

    public init(status: String?, balance: Daybalance?) {
        self.status = status
        self.balance = balance
    }


}

