//
// Daybalance.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation



public struct Daybalance: Codable {

    public var day: Int?

    public init(day: Int?) {
        self.day = day
    }


}

