//
// Daybalance.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation



public struct Daybalance: Codable {

    public var day: Int?
    public var bonus: Int?

    public init(day: Int?, bonus: Int?) {
        self.day = day
        self.bonus = bonus
    }


}

