//
// DirectionsDirectionsRoutes.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation



public struct DirectionsDirectionsRoutes: Codable {

    public var legs: [Any]?
    public var weightName: String?
    public var geometry: String?
    public var weight: Double?
    public var distance: Double?
    public var duration: Double?

    public init(legs: [Any]?, weightName: String?, geometry: String?, weight: Double?, distance: Double?, duration: Double?) {
        self.legs = legs
        self.weightName = weightName
        self.geometry = geometry
        self.weight = weight
        self.distance = distance
        self.duration = duration
    }

    public enum CodingKeys: String, CodingKey { 
        case legs
        case weightName = "weight_name"
        case geometry
        case weight
        case distance
        case duration
    }


}

