//
// DirectionsMatching.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation



public struct DirectionsMatching: Codable {

    public var code: String?
    public var tracepoints: [Any]?
    public var matchings: [Any]?

    public init(code: String?, tracepoints: [Any]?, matchings: [Any]?) {
        self.code = code
        self.tracepoints = tracepoints
        self.matchings = matchings
    }


}

