//
// Matchquality.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation



public struct Matchquality: Codable {

    public var matchcode: String?
    public var matchtype: String?
    public var matchlevel: String?

    public init(matchcode: String?, matchtype: String?, matchlevel: String?) {
        self.matchcode = matchcode
        self.matchtype = matchtype
        self.matchlevel = matchlevel
    }


}

