//
// ModelError.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation



public struct ModelError: Codable {

    public var error: String?

    public init(error: String?) {
        self.error = error
    }


}

