//
// Namedetails.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation



public struct Namedetails: Codable {

    public var name: String?

    public init(name: String?) {
        self.name = name
    }


}

